create table all_song_album
(
  track int,
  title varchar(50),
  album varchar(50)
);

insert into all_song_album
values
(1, "Baby Flower Japanese Version", "Baby Flower Japanese Version"),
(1, "Sad Girls Schemin", "love_and_pop_pt1"),
(2, "Peer", "love_and_pop_pt1"),
(3, "Baby Flower", "love_and_pop_pt1"),
(4, "Type of Girl", "love_and_pop_pt1"),
(5, "Sleek", "love_and_pop_pt1"),
(6, "I Like That", "love_and_pop_pt1"),
(7, "Me Myself Mode", "love_and_pop_pt1"),
(1, "Tokimetique", "Tokimetique"),
(2, "Tokimetique -Shin Sakiura Remix-", "Tokimetique"),
(3, "Tokimetique TV Edit", "Tokimetique"),
(1, "깨어 (Are You Alive) (Inst.)", "4study4work4inst_Vol.3"),
(2, "추리소설 (Detective Soseol) (Inst.)", "4study4work4inst_Vol.3"),
(3, "어제 우리 불꽃놀이 (Firework Diary) (Inst.)", "4study4work4inst_Vol.3"),
(4, "Love Child (Inst.)", "4study4work4inst_Vol.3"),
(5, "Persona (Inst.)", "4study4work4inst_Vol.3"),
(6, "Too Hot (Inst.)", "4study4work4inst_Vol.3"),
(7, "Diablo (Inst.)", "4study4work4inst_Vol.3"),
(8, "Friend Zone (Inst.)", "4study4work4inst_Vol.3"),
(9, "Love2Love (Inst.)", "4study4work4inst_Vol.3"),
(10, "Fly Up (Inst.)", "4study4work4inst_Vol.3"),
(11, "Cameo Love (Inst.)", "4study4work4inst_Vol.3"),
(12, "Bubble Gum Girl (Inst.)", "4study4work4inst_Vol.3"),
(13, "Q&A (Inst.)", "4study4work4inst_Vol.3"),
(14, "Christmas Alone (Inst.)", "4study4work4inst_Vol.3"),
(1, "Magic Shine New Zone", "msnz_Beyond_Beauty"),
(2, "Fly Up", "msnz_Beyond_Beauty"),
(3, "Cameo Love", "msnz_Beyond_Beauty"),
(4, "Bubble Gum Girl", "msnz_Beyond_Beauty"),
(5, "Q&A", "msnz_Beyond_Beauty"),
(6, "Christmas Alone", "msnz_Beyond_Beauty"),
(1, "Password", "tripleS_hatch!_SecretHimitsuBimil"),
(2, "Headphones", "tripleS_hatch!_SecretHimitsuBimil"),
(3, "Tokimetique", "tripleS_hatch!_SecretHimitsuBimil"),
(4, "TOKYO", "tripleS_hatch!_SecretHimitsuBimil"),
(5, "Oshare", "tripleS_hatch!_SecretHimitsuBimil"),
(6, "Untitled", "tripleS_hatch!_SecretHimitsuBimil"),
(7, "### (hatch! Version)", "tripleS_hatch!_SecretHimitsuBimil"),
(1, "Password", "tripleS hatch! <Password>"),
(1, "Pink Power", "Pink Power(잔망루피, tripleS (트리플에스))"),
(1, "@% (Alpha Percent)", "<ASSEMBLE25>"),
(2, "깨어 (Are You Alive)", "<ASSEMBLE25>"),
(3, "추리소설 (Detective Soseol)", "<ASSEMBLE25>"),
(4, "어제 우리 불꽃놀이 (Firework Diary)", "<ASSEMBLE25>"),
(5, "Love Child", "<ASSEMBLE25>"),
(6, "Persona", "<ASSEMBLE25>"),
(7, "Too Hot", "<ASSEMBLE25>"),
(8, "Diablo", "<ASSEMBLE25>"),
(9, "Friend Zone", "<ASSEMBLE25>"),
(10, "Love2Love", "<ASSEMBLE25>"),
(1, "Girls Never Die (Japanese Version)", "Girls Never Die (Japanese Version)"),
(1, "Rising (Japanese Version)", "Rising (Japanese Version)"),
(4, "PainDrop (by 서연, 지우, 유빈, 소현)", "선의의 경쟁 OST"),
(1, "PainDrop (by 서연, 지우, 유빈, 소현)", "선의의경쟁 OST Part.4"),
(2, "PainDrop (by 서연, 지우, 유빈, 소현) (Inst)", "선의의경쟁 OST Part.4"),
(1, "Dreaming (by 유연, 유빈, 다현, 시온)", "Dreaming (골 때리는 그녀들 X tripleS (트리플에스))"),
(2, "Dreaming (by 유연, 유빈, 다현, 시온)", "Dreaming (by 유연, 유빈, 다현, 시온) (Inst.)"),
